spring:
  application:
    name: eureka-server

server:
  port: 9001

eureka:
  instance:
    hostname: backup1
  client:
    register-with-eureka: true #不作为服务注册
    fetch-registry: true #单点服务不需要同步其他服务数据
    service-url:
      defaultZone: http://master:9000/eureka/,http://backup2:9002/eureka/